### ISSUE TITLE
Cannot unpack file /temp/pip-unpack-0w6x6i6c/dopyapi.git

### ISSUE THREAD

**Issue by meseguera** [mohsenSy/dopyapi#1]
Error: Cannot determine archive format of /tmp/pip-req-build-44x5yx7e

**Comment by mohsenSy** [comment]
@meseguera 

Could you please describe how did you try to install the library and you got this error?

I use these commands to create a virtual environment and install the library in it

```
python3 -m venv venv
source venv/bin/activate
pip3 install --upgrade wheel
pip3 install git+git://github.com/mohsenSy/dopyapi.git
```

Please try these commands and let me if it works or not?
